### ISSUE TITLE
private?

### ISSUE THREAD

**Issue by jorgtron** [recruitmilitary/spree-product-expiration#2]
Hi, is this extension currently private? https://github.com/recruitmilitary/spree-product-expiration.git does not seem to work, and my app fails to install it.

**Comment by mguterl** [comment]
should be public, try this URL
https://github.com/recruitmilitary/spree-product-expiration

On Tue, Aug 16, 2011 at 4:28 PM, jorgtron
reply@reply.github.com
wrote:

**Comment by jorgtron** [comment]
nevermind, I made a silly mistake :)

2011/8/16 mguterl <
reply@reply.github.com>

> should be public, try this URL
> https://github.com/recruitmilitary/spree-product-expiration
> 
> On Tue, Aug 16, 2011 at 4:28 PM, jorgtron
> reply@reply.github.com
> wrote:
> 
> > Hi, is this extension currently private?
> > https://github.com/recruitmilitary/spree-product-expiration.git does not
> > seem to work, and my app fails to install it.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/recruitmilitary/spree-product-expiration/issues/2
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/recruitmilitary/spree-product-expiration/issues/2#issuecomment-1820529

## 

Jrgen Tronstad
http://www.interaksjonsdesigner.no
